export enum UserProfileResources {
	USERPROFILE_VIEW = 'USERPROFILE_VIEW',
	USERPROFILE_CREATE = 'USERPROFILE_CREATE',
	USERPROFILE_UPDATE = 'USERPROFILE_UPDATE',
	USERPROFILE_REMOVE = 'USERPROFILE_REMOVE'
}
